# Site settings
title: Travel Blog Cerf
email: traveleando@gmail.com
description: A demo blog about creating a Jekyll Site on GitHub
baseurl: "/travel-blog"

twitter_username: guilh
avatar: "" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Cerf" # Set default author name
      categories: "places"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
